### ISSUE TITLE
Update `galah_geolocate` documentation (& functionality?)

### ISSUE THREAD

**Issue by daxkellie** [AtlasOfLivingAustralia/galah#125]
It might not be clear to users how to use a shapefile with `galah_geolocate` or how to edit that shape file using the `sf` package to make it work with `galah_geolocate`. For example, often shape files are too complex for `galah_geolocate`, and so it would be worth explaning how to deal with this error with information like:
```r
# If your polygon is too complex, simplify with st_simplify()
library(sf)
sf::sf_use_s2(FALSE)
map <- sf::read_sf("victoria.shp")
map_simplified <- sf::st_simplify(map, dTolerance = 0.05)
```

**Comment by mjwestgate** [comment]
`galah_geolocate` hasn't had much attention, but could probably use some. A few potentially worthwhile improvements might include:

- Using bounding boxes as inputs; though an easier workflow might be to passing inputs to `galah_filter` via fields such as `decimalLatitude` and `decimallLongitude`
- Supporting circular queries by passing lat, long and radius; supported by the 'Get points of interest (POI) within a circle' API, but not called by `galah` at present
- Allowing users to upload shapefiles to affect later queries; again possible via the API but unclear what workflow would be needed to make this work

**Comment by mjwestgate** [comment]
Discussion 2022-02-08 led to following proposal:

- `galah_polygon()` to replace current `galah_geolocate` functionality, supporting `wkt` strings. Add complexity limit (11 vertices?)
- `galah_radius` to specify a circle as per 'explore your area' tool
- `galah_bbox` to extract a bounding box from an `sf` object or shapefile, and pass that to `galah_polygon`

One final option (not discussed) is to retain `galah_geolocate` as a wrapper function to the above arguments. Unclear whether this would be more or less confusing for users.

**Comment by mjwestgate** [comment]
completed with `galah_bbox` and `galah_polygon`
