### ISSUE TITLE
Should there be a `galah_profile` function?

### ISSUE THREAD

**Issue by mjwestgate** [AtlasOfLivingAustralia/galah#130]
Currently, users set a profile as an optional argument within `galah_filter`. This is weird for a few reasons:

- setting the profile doesn't add any rows to the resulting `tibble`; instead the profile name is added as an attribute, which is not standard behavior for any other `galah_` function
- there is a lookup function associated with profiles (`show_all_profiles`), but no corresponding `galah_` function
- calling the profiles argument within `galah_filter` is awkward because it doesn't use NSE. In practice, this results in combining calls that use `=` and `==` within the same function (e.g. `galah_filter(year == 2020, profile = "ALA")`), which is confusing

Alternate behaviour would be to allow piping of profiles specifically through its' own function, such as:
```
galah_call() |>
  galah_filter(year >= 2010) |>
  galah_profile(ALA) |>
  atlas_counts()
```

**Comment by mjwestgate** [comment]
Proposed name change to something more informative, e.g. `galah_quality_profile`

**Comment by daxkellie** [comment]
A decision was made to make the name `galah_apply_profile()` to keep the verbing language consistent for `galah_` functions (e.g., `select`,`filter`, `group_by`). Name might require revisiting in the future
