### ISSUE TITLE
Provide documentation for galah_config() (warning?) message

### ISSUE THREAD

**Issue by stewartmacdonald** [AtlasOfLivingAustralia/galah#136]
When I call `galah_config(email = "email@example.com")` to set my email address, I get the following message:
```
> galah_config(email = "email@example.com")
These configuration options will only be saved for this session.
    Set `preserve = TRUE` to preserve them for future sessions.
```
Adding `preserve = TRUE` to `galah_config()` results in an error. It would be good to put something in the `galah_config()` documentation about that message (or remove it if it no longer applies).

**Comment by daxkellie** [comment]
`preserve = TRUE` option message was removed in commit 124487587d19a88e8e140125bd85f25937c976f6 and updated to `profile_path` arg. Decision was made to avoid users from saving options to increase reproducibility
