### ISSUE TITLE
Package `wellknown` about to be archived on CRAN

### ISSUE THREAD

**Issue by mjwestgate** [AtlasOfLivingAustralia/galah#141]
As per [this issue](https://github.com/ropensci/wellknown/issues/36), The ROpenSci package `wellknown` is due to be archived soon. Once that happens it is possible that `galah` will be archived too, as `wellknown` is listed in `Imports` for `galah`. The easy fix to this is to switch to depending on package `wk` instead.

**Comment by daxkellie** [comment]
Updated `NAMESPACE` after commit a707cdf6a7a0eab5ce78c5179e39dde146e8a7ad no longer lists {wellknown} in package `Imports`
