### ISSUE TITLE
ala_occurrences taxa argument: "Error: taxa is not a character vector"

### ISSUE THREAD

**Issue by shawnlaffan** [AtlasOfLivingAustralia/galah#45]
(Edited to fix copy-paste error)

Running galah under R 3.6 produces this error:

```
Error: taxa is not a character vector
```

```r
  search_term = list (genus = "Corymbia", kingdom="Plantae")
  occ <- ala_occurrences(
    taxa      = select_taxa(query = search_term),
  )
```

Code works without issue on 4.03.

Occurs with both CRAN and dev versions.  

Shawn.

**Comment by mjwestgate** [comment]
Hi Shawn,

Thanks for this. I hope you're enjoying `galah`, despite the occasional bug! We'd actually seen similar behaviour ourselves and are preparing an update to the effect that `galah` is only reliable for R 4.0+ (we'll do some testing to get the exact version, but I suspect that will be correct). That should avoid the problem, if only by avoiding installation on older versions in the first place.

If there is some reason why it's critical for this to run on older versions of R, let us know and we can reach a decision about whether to chase this bug further.

Martin

**Comment by shawnlaffan** [comment]
Setting the minimum version to 4.x is probably the way to go as there are likely to be other similar issues lurking in the code.  Trying to support v3 will lead to needless complexity and chew up developer time.  

The only reason I'm trying 3.6 is because the ecocloud R instances are still using it, but an upgrade is on the cards for the near future.
