### ISSUE TITLE
Empty list (select_taxa)

### ISSUE THREAD

**Issue by ShawanChowdhury** [AtlasOfLivingAustralia/galah#63]
I was cross-checking EPBC listed species with the ALA data using the 'select_taxa()' function. It worked for other species list (e.g., weeds of national significance) but I obtained an empty list for the EPBC listed species.

**galah version**
1.1.0

**To Reproduce**
threatened_list <- fread("EPBC_list.csv")
threatened_ala <- select_taxa(threatened_list$scientific_name)

**Comment by matildastevenson** [comment]
Hi Shawan, can you provide the EPBC list here?

**Comment by ShawanChowdhury** [comment]
Here it is.
[EPBC_list.xlsx](https://github.com/AtlasOfLivingAustralia/galah/files/6837657/EPBC_list.xlsx)

**Comment by matildastevenson** [comment]
`select_taxa` is assuming that a list of identifiers, rather than scientific names, has been provided because there are numeric characters in some rows. If you remove the numbers it should work as expected

**Comment by matildastevenson** [comment]
This will be addressed in #64
