### ISSUE TITLE
Add override for `select_taxa` so user can manually specify whether names or identifiers have been provided

### ISSUE THREAD

**Issue by matildastevenson** [AtlasOfLivingAustralia/galah#64]

**Comment by mjwestgate** [comment]
Not sure what approach you’re taking here, but there might be an argument for splitting this into two different functions:

- search_taxa() for searching for strings (consistent with search_fields())
- select_taxa() for supplying a uid

Just an idea though.

**Comment by matildastevenson** [comment]
I think this could work- some additional thoughts:
- `search_taxa()` would take two of the additional arguments currently taken by `select_taxa`- `children`, and `all_ranks`
- The `counts` argument in `select_taxa` would be removed, and users encouraged to use `ala_counts(group_by = 'speciesID')` to get the same information
- `select_taxa` would accept ids or strings- and would assume that a user had checked that the string was what they wanted
- `select_taxa` would have to accept ids generated by `taxize`
- `select_taxa` could just have `...` as the argument- this would make it nicely consistent with the other `select_` functions
- Functionality in `search_taxa` could be duplicated in `taxize` (and potentially eventually replaced)- making it possibly worth importing `taxize` into the package
- `ala_species` will stay as is, because it enables listing species by area/matching filters etc.- and the other taxa functions don't do this. To avoid confusion, I think it is good to keep it as `ala_species` as opposed to `ala_taxa`. If users want information for other ranks it is just a subset of what is returned by `ala_species`. It would be good for `ala_species` to return intermediate rank information, but I think this change should be made on the ALA side rather than in galah.
