### ISSUE TITLE
`select_taxa` returns incorrect IDs for more specific search terms

### ISSUE THREAD

**Issue by T-LeB** [AtlasOfLivingAustralia/galah#96]
**Describe the bug**
When i run the ala_occurrences and select_taxa functions with a list of 360 target species they are returning a collection of occurrence with issues including:
- excluding species or subspecies that are on the list and otherwise present in ALA online
- including species or subspecies that aren't on the list and which dont appear to be taxonomic synonyms of species on the list
- returning records without the species name

I think what may be happening is whatever values select_taxa is providing to the ala_occurrences functions are slightly wrong or generalised possibly. If I run select_taxa over the list on its own every species has an exactly matched ScientificName but the species column excludes subspecies and species not formally described. 

**galah version**
1.31

**To Reproduce**
Steps to reproduce the behaviour:

1. Read in target_species.csv (attached)
[target_species.csv](https://github.com/AtlasOfLivingAustralia/galah/files/7327225/target_species.csv)

2. Run the following code chunk using galah package
ala_recs <- ala_occurrences(taxa = select_taxa(target_species$ScientificName))

**Expected behaviour**
What I would expect to happen is that the ala_occurrences function returns all available records of the species in the target_species data frame and only these species. 

**Additional context**
All species in this list are taxonomically valid (currently) even though some are not formally described and all can and have been searched for manually as they are spelt in this list into ALA online and return results correctly. So the records are there they just dont seem to be returning to me for some species. While also returning additional species not on the list in other cases.

**Comment by T-LeB** [comment]
Hi Dax

Thanks for that run through, it certainly makes more sense how the select_taxa function is working now. Although this doesnt quite address the problem I was referring to in my last response but I might not have understood where the issue was well enough to explain myself. 

From what you've said here the select_taxa function is working as it should and that species column for whatever reason only includes formally described species. However, I think when it passes the list of matched species to the ala_occurrences function something is going wrong and these unnammed species (Bertya sp. (Chambigne NR, M. Fatemi 24), Eucalyptus sp. cattai etc) are getting lost in the process even though there are exact matches being found and they have some value in the taxon_concept_id column. 

I wanted to make sure i wasnt just missing something so i ran that missing species code chunk on the full target_species list provided above and modified it so i'd only get the species that werent in my original list rather than the species that had been added in error like all the extra Diuris. For reference: 

target_taxa_in_taxa <- ala_recs_names %>% 
  as_tibble() %>% 
  filter(species %in% target_species$ScientificName)

missing_taxa_in_taxa <- target_species %>% 
  as_tibble() %>% 
  filter(!ScientificName %in% target_taxa_in_taxa$species)

There are 50 taxa on the original list that arent in the ala_occurrences output. Some are instances were they are there but under another name that ALA's taxonomy has corrected (e.g. Commersonia procumbens -> Androcalva procumbens). Some are subspecies that ALA has decided to ignore the subspecies (e.g. Boronia inflexa subsp. torringtonensis -> Boronia inflexa). But most are these undescribed species that end up as NA in the species column of the select_taxa output.

To check your filter by taxon_concept_id workaround I looked through all the possible fields that could be included in the output and included every one that sounds relevant to species identification and that you could use in combination with the select_taxa output dataframe to match records to species.

ala_recs <- ala_occurrences(taxa = select_taxa(target_species$`Scientific Name`),
                            filters = select_filters(stateProvince = "New South Wales",
                                                      basisOfRecord = c("HUMAN_OBSERVATION","PRESERVED_SPECIMEN")),
                             columns = select_columns("raw_scientificName",
                                                      "scientificName",
                                                      "species",
                                                      "scientificNameID",
                                                      "taxonConceptID"))

If you filter any of these columns by the original search terms, from target_species list or the matched taxon_concept_ID from the select_taxa output of most of the 50 missing species that are unnamed.

I think this is because when select_taxa is parsed to ala_occurences whichever column is used to sent off to ALA to compile the records has the wrong data in it, which i think must be either the taxon_concept_ID column and/or the species column because it won't recognise the taxon_concept_ID for some of these taxa when its in the format ALA_Bertya_sp_Chambigne_NR_M_Fatemi_24. but it will for others e.g. Eucalyptus sp. Cattai. Apparently, because on their respective ALA pages they do or dont have these identifiers linked (e.g. https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2892151#names). The subspecies i dont understand because their taxon_concept_id is correct but i guess it might relate to the species column excluding the subspecies. 

I understand this probably falls outside of the scope of the actual workings of the Galah package and that theres ongoing work to improve and streamline ALA. But from a user standpoint its pretty opaque and unintuitive when the same search terms return the correct results online, I've only happened to catch this issue by chance and then its taken me getting your help and spending few hours over a couple of days to understand the depth of it and i still have to go and figure out a workaround that can fit into a repeatable workflow. 

I appreciate your time and help in working through this though and in general think the package is a massive help in using ALA data.

**Comment by T-LeB** [comment]
Thanks for that breakdown and all your time and help on this, i think between what you've explained here and a little manual wrangling i should be able to come up with a work around now.

**Comment by daxkellie** [comment]
Great news!

For easier reference, here is a summary of the identified issue outside of our discussion: 

`select_taxa()` sometimes does not find correct `taxon_concept_ids` when a search term is correctly identified as an existing species in the ALA but contains parentheses. Fixing this will improve the flexibility of `select_taxa()`
``` r
# search terms with parentheses
taxa <- select_taxa(c("Bertya sp. (Chambigne NR, M. Fatemi 24)",
                      "Bertya sp. (Clouds Creek, M. Fatemi 4)",
                      "Diuris sp. (Oaklands, D.L. Jones 5380)"))

taxa$taxon_concept_id
#> [1] "ALA_Bertya_sp_Chambigne_NR_M_Fatemi_24"
#> [2] "ALA_Bertya_sp_Clouds_Creek_M_Fatemi_4" 
#> [3] "ALA_Diuris_sp_Oaklands_D_L_Jones_5380"

# Pass IDs to ala_occurrences
occs <- ala_occurrences(taxa = select_taxa(taxa$taxon_concept_id, is_id = TRUE))
#> Error in check_count(count): This query does not match any records.


# search terms without parentheses
taxa <- select_taxa(c("Bertya sp. Chambigne NR, M. Fatemi 24",
                      "Bertya sp. Clouds Creek, M. Fatemi 4",
                      "Diuris sp. Oaklands, D.L. Jones 5380"))

taxa$taxon_concept_id
#> [1] "https://id.biodiversity.org.au/node/apni/2892151"  
#> [2] "https://id.biodiversity.org.au/node/apni/2907136"  
#> [3] "https://id.biodiversity.org.au/taxon/apni/51290527"

# Pass IDs to ala_occurrences
occs <- ala_occurrences(taxa = select_taxa(taxa$taxon_concept_id, is_id = TRUE))
#> This query will return 49062 records
```
